#!/bin/bash

clear

# set log info
logPath="/var/log/install"
sudo rm -rf $logPath
sudo mkdir $logPath


# Pre-update steps

# Owncloud PPT
echo "deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_$(grep ^DISTRIB_RELEASE= /etc/lsb-release | cut -d= -f2)/ /" | sudo tee -a /etc/apt/sources.list.d/owncloud.list
wget http://download.opensuse.org/repositories/isv:ownCloud:desktop/xUbuntu_$(grep ^DISTRIB_RELEASE= /etc/lsb-release | cut -d= -f2)/Release.key -O - | sudo apt-key add -

# Update existing
echo -e "\e[1m\e[32mUpdate existing packets...\e[0m\e[39m"
sudo apt-get -y update
echo -e "\e[1m\e[32mDone.\e[0m\e[39m"

echo -e "\e[1m\e[32mUpgrade existing packets...\e[0m\e[39m"
sudo apt-get -y upgrade
echo -e "\e[1m\e[32mDone.\e[0m\e[39m"

# list of APT main packages to install
packages=('git' 'git-flow' 'php7.0' 'php7.0-mysql' 'apache2' 'libapache2-mod-php7.0' 'php-xml' 'mysql-server' 'poedit' 'terminator' 'filezilla' 'vlc' 'browser-plugin-vlc' 'owncloud-client' 'revelation' 'default-jre' 'default-jdk' 'composer' 'curl' 'gimp')

for i in ${!packages[*]}
do
  	echo -e "\e[1m\e[32mInstalling package ${packages[$i]}...\e[0m\e[39m"	
	sudo apt-get install -qy ${packages[$i]}
	echo -e "\e[1m\e[32mDone.\e[0m\e[39m"

	# Last config
	case "${packages[$i]}" in
	"apache2")
		echo -e "\e[1m\e[32mComplementary steps for ${packages[$i]} \e[0m\e[39m"
		sudo chown -R nicolas:www-data /var/www/html
		sudo chmod g+s /var/www/html
		sudo sed -i.bak s/APACHE_RUN_USER=www-data/APACHE_RUN_USER=nicolas/g /etc/apache2/envvars
		sudo service apache2 restart
		ln -s /var/www/html ~/sites
		
		;;
	"git")
		echo -e "\e[1m\e[32mComplementary steps for ${packages[$i]} \e[0m\e[39m"
		git config --global user.name "Nicolas BONNIOT"
		git config --global user.email "nicolas@devgiants.fr"
		;;
	esac
done

# Adminer
sudo mkdir /usr/share/adminer
sudo wget "http://www.adminer.org/latest.php" -O /usr/share/adminer/latest.php
sudo ln -s /usr/share/adminer/latest.php /usr/share/adminer/adminer.php
echo "Alias /adminer.php /usr/share/adminer/adminer.php" | sudo tee /etc/apache2/conf-available/adminer.conf
sudo a2enconf adminer.conf
sudo service apache2 restart


# Chrome
echo -e "\e[1m\e[32mInstalling Chrome...\e[0m\e[39m"

chromeInstalled=$(dpkg-query -W --showformat='${Status}\n' google-chrome-stable|grep "install ok installed")

if [ "" == "$chromeInstalled" ]; then
	sudo apt-get install -qy libxss1 libappindicator1 libindicator7
	wget --output-document chrome https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
	sudo dpkg -i chrome
	sudo apt-get install -fqy
	rm -rf chrome
else
	echo -e "\e[1m\e[32mAlready installed.\e[0m\e[39m"
fi
echo -e "\e[1m\e[32mDone.\e[0m\e[39m"

# Skype
echo -e "\e[1m\e[32mInstalling Skype...\e[0m\e[39m"

skypeInstalled=$(dpkg-query -W --showformat='${Status}\n' skype|grep "install ok installed")


if [ "" == "$skypeInstalled" ]; then
	sudo apt-get install libqt4-dbus libqt4-network libqt4-xml libasound2
	wget --output-document skype http://www.skype.com/go/getskype-linux-beta-ubuntu-64
	sudo dpkg -i skype
	sudo apt-get -fqy install
	rm -rf skype
	echo -e "\e[1m\e[32mDone.\e[0m\e[39m"
else
	echo -e "\e[1m\e[32mAlready installed.\e[0m\e[39m"
fi

# Team Viewer

# Php storm 9
echo -e "\e[1m\e[32mPHP Storm 9...\e[0m\e[39m"
phpstormDirectory="$HOME/phpstorm"
if [ ! -d "$phpstormDirectory" ]; then
	wget "http://download.jetbrains.com/webide/PhpStorm-9.0.tar.gz"
	mkdir phpstorm && tar xfz PhpStorm-*.tar.gz -C phpstorm
	sudo sh phpstorm/PhpStorm-141.1912/bin/phpstorm.sh
	echo -e "\e[1m\e[32mDone.\e[0m\e[39m"
else
	echo -e "\e[1m\e[32mAlready installed.\e[0m\e[39m" 
fi


# Printer software
echo -e "\e[1m\e[32mPrinter software...\e[0m\e[39m"

hplipInstalled=$(dpkg-query -W --showformat='${Status}\n' hplip|grep "deinstall ok config-files")

if [ "" == "$hplipInstalled" ]; then
	sudo apt-get install -y --assume-yes avahi-utils libcups2 cups libcups2-dev cups-bsd cups-client libcupsimage2-dev libdbus-1-dev build-essential ghostscript openssl libjpeg-dev libsnmp-dev snmp-mibs-downloader libtool libusb-1.0.0-dev wget policykit-1 policykit-1-gnome python3-dbus python3-gi python3-dev python3-notify2 python3-pil python3-pyqt4 gtk2-engines-pixbuf python3-dbus.mainloop.qt python3-reportlab python3-lxml libsane libsane-dev sane-utils xsane
	wget --output-document hplip.run "http://downloads.sourceforge.net/project/hplip/hplip/3.15.9/hplip-3.15.9.run?r=&ts=1442571881&use_mirror=skylink"
	bash hplip.run
	rm -rf hp*
	echo -e "\e[1m\e[32mDone.\e[0m\e[39m"
else
        echo -e "\e[1m\e[32mAlready installed.\e[0m\e[39m"
fi

# RVM
echo -e "\e[1m\e[32mRVM...\e[0m\e[39m"
rvmInstalled=$(env | grep "rvm")
if [ "" == "$rvmInstalled" ]; then
	sudo apt-get install libgdbm-dev libncurses5-dev automake libtool bison libffi-dev
	gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
	\curl -sSL https://get.rvm.io | bash -s stable
	source ~/.rvm/scripts/rvm
	rvm install 2.2.3
	rvm use 2.2.3 --default
	ruby -v

	# SASS
	#rvm all do gem install sass
	gem install sass

	# Capistrano
	gem install capistrano

	# Symfony for capistrano
	gem install capistrano-symfony

	# Composer for capistrano
	gem install capistrano-composer

	echo -e "\e[1m\e[32mDone.\e[0m\e[39m"
else
        echo -e "\e[1m\e[32mAlready installed.\e[0m\e[39m"
fi

#  Simple vhost creator
mkdir ~/scripts
git clone https://github.com/devgiants/simple-vhost-creator.git ~/scripts/simple-vhost-creator
chmod +x ~/scripts/simple-vhost-creator/vhost-creator
sudo ln -s ~/scripts/simple-vhost-creator/vhost-creator /usr/bin/vhost-creator
sudo ln -s ~/scripts/simple-vhost-creator/vhost_template.conf /usr/bin/vhost_template.conf

# Git aware prompt
mkdir ~/.bash
git clone https://github.com/jimeh/git-aware-prompt.git ~/.bash/gap

echo "# Add Git aware prompt" >> ~/.bashrc
echo "export GITAWAREPROMPT=~/.bash/gap" >> ~/.bashrc
echo "source \"\${GITAWAREPROMPT}/main.sh\"" >> ~/.bashrc
echo "export PS1=\"\\\${debian_chroot:+(\\\$debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] \[\$txtcyn\]\\\$git_branch\[\$txtred\]\\\$git_dirty\[\$txtrst\]\\\$ \"" >> ~/.bashrc

source ~/.bashrc

# Set favorites
echo -e "\e[1m\e[32mSet favorites.\e[0m\e[39m"
dconf write /org/gnome/shell/favorite-apps "['nautilus.desktop', 'terminator.desktop', 'google-chrome.desktop', 'filezilla.desktop','gedit.desktop', 'revelation.desktop', 'skype.desktop', 'gcalctool.desktop']"

# Set list view as default one for nautilus
gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'

# auto clean
sudo apt-get autoclean
sudo apt-get autoremove -y

sudo reboot
